#!/bin/sh

ACT=$1
RUN=$2
OPT=$3
if [ "$1" = "-h" -o -z "$ACT" -o -z "$RUN" ]; then
  echo "Usage $0 ACT RUN [OPT]"
  echo "   or $0 ACT RUN_FILE [OPT]"
  echo "  Top level fcl is ACT.fcl"
  echo "  RUN = run number or RUN_FILE"
  echo "  OPT = option for duneproc, e.g. retry"
  exit 0
fi
FRUN=$RUN
if ! echo $FRUN | grep _ 2>/dev/null 1>/dev/null; then
  while [ ${#FRUN} -lt 6 ]; do FRUN=0$FRUN; done
fi
OUTDIR=$HOME/xfer/$(date +%Y)/$(date +%m%d)/$ACT/run$FRUN
RUNDIR=$ACT/vdtcb$FRUN

# Check the fcl exists
REM=$ACT
while [ $REM != . ]; do
  FCL=$(basename $REM)
  if ! fcldump $FCL.fcl 2>&1 1>/dev/null; then
    echo Skipping Fcl not found: $FCL.fcl
    #exit 1
  fi
  REM=$(dirname $REM)
done

if [ ! -r $OUTDIR ]; then
  echo Creating output directory $OUTDIR
  mkdir -p $OUTDIR
fi

vdtcbFindFiles $(basename $RUN) -
DSNAME=vdtcb$FRUN
DSFILE=$HOME/data/dune/datasets/vdct/$DSNAME.txt
if [ ! -r $DSFILE ]; then
  echo Unable to find $DSFILE
  exit 2
fi
echo duneproc $ACT vdtcb$FRUN $OPT
duneproc $ACT $DSNAME $OPT
echo Output directory: $OUTDIR
cp $RUNDIR/*.png $RUNDIR/*.tpad $OUTDIR
ls -ls $OUTDIR
