#!/bin/sh

# Read the flags.
DET=
while true; do
  if [ $# -lt 3 -o "$1" = "-h" ]; then
    echo "Usage $0 [-t] [-b] ACT RUN EVT [OPT]"
    echo "   -t: Run type is vdtcb (vertical-drift, top electronics coldbox)"
    echo "   -b: Run type is vdbcb (vertical-drift, bottom electronics coldbox)"
    echo "  ACT: Top level fcl is ACT.fcl"
    echo "  RUN: run number"
    echo "  EVT: event number"
    echo "  OPT: option for duneproc, e.g. retry"
    exit 0
  elif [ ${1:0:1} != '-' ]; then
    break
  elif [ "$1" = "-b" ]; then
    DET=vdbcb
  elif [ "$1" = "-t" ]; then
    DET=vdtcb
  else:
    echo Invalid flag:$1
    exit 1
  fi
  shift
done

ACT=$1
RUN=$2
EVT=$3
OPT=$4
if ! [ $RUN -eq $RUN ] 2>/dev/null; then
  echo RUN must be a number: $RUN
  exit 1
fi
if ! [ $EVT -eq $EVT ] 2>/dev/null; then
  echo EVT must be a number: $EVT
  exit 1
fi

if [ -z "$DET" ]; then
  if [ ${ACT:0:3} = vdt ]; then
    DET=vdtcb
  elif [ ${ACT:0:3} = vdb ]; then
    DET=vdbcb
  else
    echo Unable to determine if this is top or bottom data.
    echo Add flag -t or -b.
    exit 1
  fi
fi

FRUN=$RUN
if ! echo $FRUN | grep _ 2>/dev/null 1>/dev/null; then
  while [ ${#FRUN} -lt 6 ]; do FRUN=0$FRUN; done
fi
FEVT=$EVT
DSNAME=$DET-$FRUN-$FEVT
while [ ${#FEVT} -lt 3 ]; do FEVT=0$FEVT; done
OUTDIR=$HOME/xfer/$(date +%Y)/$(date +%m%d)/$ACT/run$FRUN
RUNDIR=$ACT/$DSNAME

# Check the fcl exists
REM=$ACT
while [ $REM != . ]; do
  FCL=$(basename $REM)
  if ! fcldump $FCL.fcl 2>&1 1>/dev/null; then
    echo Skipping Fcl not found: $FCL.fcl
    #exit 1
  fi
  REM=$(dirname $REM)
done
if [ ! -r $OUTDIR ]; then
  echo Creating output directory $OUTDIR
  mkdir -p $OUTDIR
fi

echo duneproc $ACT $DSNAME $OPT
duneproc $ACT $DSNAME $OPT
echo Output directory: $OUTDIR
cp $RUNDIR/*.png $RUNDIR/*.tpad $OUTDIR
ls -ls $OUTDIR
