#!/bin/sh
#
# start-shell
#
# David Adams
# May 2022
#
# Start a bash shell to run the analysis scripts here.
#
# User must first have set up dunerun.

DRV=$(dunerunVersion 2>/dev/null)
if [ -z "$DRV" ]; then
  echo Please first set up dunerun.
  exit 1
fi

dunerun-check-proxy
if hostname | grep ^dunegpvm 1>/dev/null; then
  dune-run -e dunesw,duneproc shell
else
  dune-run -e dunesw,xrdhdf5,duneproc shell
fi
