#!/bin/sh
#
# start-shell
#
# David Adams
# May 2022
#
# Start a bash shell to run the analysis scripts here.
#
# User must first have set up dunerun.

DUV=$1
DRV=$(dunerunVersion 2>/dev/null)
if [ -z "$DRV" ]; then
  echo Setting up a local installation of dunerun and duneproc.
  source ./setup_deps.sh $DUV
  DRV=$(dunerunVersion 2>/dev/null)
fi

if [ -z "$DRV" ]; then
  echo It appears dunerun is still not set up.
  exit 1
fi

dunerun-check-proxy
if hostname | grep ^dunegpvm 1>/dev/null; then
  dune-run -e dunesw,xrdhdf5,duneproc shell
else
  dune-run -e dunesw,xrdhdf5,duneproc shell
fi
